#!/bin/sh
#
# This file is distributed under the terms of the MIT License.
# See the LICENSE file at the top of this tree, or if it is missing a copy can
# be found at http://opensource.org/licenses/MIT
#

dir=$(dirname $0)
cd "${dir}"

exec ./configure --host=arm-none-eabi --with-chip=STM32F103ZG --enable-debug $*
