#!/bin/sh
#
# This file is distributed under the terms of the MIT License.
# See the LICENSE file at the top of this tree, or if it is missing a copy can
# be found at http://opensource.org/licenses/MIT
#
# Make everything

dir=$(dirname $0)
cd "${dir}"

make=make
[ -x /usr/bin/gmake ] && make=gmake

do_bootstrap=

if [ -f configure ]; then
	if find . -type f '(' -name 'Makefile.*' -or -name 'configure.*' -or -name '*.in' ')' -newer configure | grep -q "."; then
		do_bootstrap=y
	fi
else
	do_bootstrap=y
fi
if [ "$do_bootstrap" ]; then
	./bootstrap
	./do-configure-arm
	$make clean
fi

exec $make
