/** AUTOGENERATED FILE! DO NOT EDIT MANUALLY!
 * \file include/version.h
 *
 * \author Chris Luke <chrisy@flirble.org>
 * \copyright Copyright (c) Chris Luke <chrisy@flirble.org>
 *
 * \copyright This file is distributed under the terms of the MIT License.
 * See the LICENSE file at the top of this tree, or if it is missing a copy can
 * be found at http://opensource.org/licenses/MIT
 */

#ifndef _VERSION_H
#define _VERSION_H

#define PROJECT_NAME "FreeRTOS-test"
#define PROJECT_VERSION "0.3"
#define PROJECT_COPYRIGHT "(c) 2014 Chris Luke"

#endif /* _VERSION_H */
